# Generated by Django 5.2.4 on 2025-07-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=32)),
                ('update_time', models.DateField()),
                ('created_datetime', models.DateField()),
                ('title', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=320)),
                ('ip_andress', models.GenericIPAddressField()),
            ],
        ),
    ]
