# Generated by Django 5.2.4 on 2025-07-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postit',
            name='_id',
        ),
        migrations.AlterField(
            model_name='postit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
