# Generated by Django 5.2.4 on 2025-07-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_remove_postit__id_alter_postit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
