# Generated by Django 5.2.4 on 2025-07-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_postit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='created_datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postit',
            name='ip_andress',
            field=models.GenericIPAddressField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='postit',
            name='update_time',
            field=models.DateField(blank=True),
        ),
    ]
