# Generated by Django 5.2.4 on 2025-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_postit_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='ip_andress',
            field=models.GenericIPAddressField(auto_created=True, null=True),
        ),
    ]
