# Generated by Django 5.2.4 on 2025-07-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_postit_ip_andress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='update_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
