# Generated by Django 5.2.4 on 2025-07-29 20:08

import django.http.request
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_alter_postit_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='ip_andress',
            field=models.GenericIPAddressField(),
        ),
    ]
