# Generated by Django 5.2.4 on 2025-07-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_postit_ip_andress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='ip_andress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
