# Generated by Django 5.2.4 on 2025-07-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_alter_postit_ip_andress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postit',
            name='ip_andress',
        ),
    ]
