# Generated by Django 5.2.4 on 2025-07-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_remove_postit_ip_andress'),
    ]

    operations = [
        migrations.AddField(
            model_name='postit',
            name='creator',
            field=models.CharField(default='Anon', max_length=320),
        ),
        migrations.AlterField(
            model_name='postit',
            name='update_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
