# Generated by Django 5.2.4 on 2025-07-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_postit_creator_alter_postit_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='postit',
            name='ip_andress',
            field=models.GenericIPAddressField(auto_created=True, null=True),
        ),
    ]
