# Generated by Django 5.2.4 on 2025-07-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_postit_ip_andress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='username',
            field=models.CharField(auto_created=True, max_length=32),
        ),
    ]
